services:
  backend:
    build: !reset null
    image: ${BACKEND_IMAGE}
    ports: !reset []

  postgres:
   ports: !override
    - "127.0.0.1:${POSTGRES_PORT:-5433}:5432"

  frontend:
    build: !reset null
    image: ${FRONTEND_IMAGE}
    ports: !override
      - "127.0.0.1:${FRONTEND_PORT:-3001}:80"
